Repository ASFHyP3/OPERA-DISP-TMS, pull requests merged in 2024-12, with the labels that each got.

#43 jth edits for hyp3 plugin
  Dockerfile
  src/opera_disp_tms/generate_opera_disp_tile.py
Labels: bumpless

#41 add create-jira-issue workflow
  .github/workflows/create-jira-issue.yml
Labels: bumpless

#46 Remove cli entrypoint "velocity" option
  src/opera_disp_tms/generate_opera_disp_tile.py
Labels: bumpless

#47 Move CLI Entrypoint for `generate_opera_disp_tile.py` into `__main__.py`
  src/opera_disp_tms/__main__.py
  src/opera_disp_tms/generate_opera_disp_tile.py
Labels: bumpless

#48 tag all uploaded files as products, drop hyp3lib dependency
  environment.yml
  pyproject.toml
  src/opera_disp_tms/__main__.py
  src/opera_disp_tms/tmp_s3_access.py
  src/opera_disp_tms/utils.py
  tests/test_tmp_s3_access.py
  tests/test_utils.py
Labels: bumpless

#50 clean up hyp3 entrypoint
  pyproject.toml
  src/opera_disp_tms/__main__.py
  src/opera_disp_tms/generate_opera_disp_tile.py
  tests/test_generate_opera_disp_tile.py
  tests/test_main.py
Labels: bumpless

#49 Refactors and Consistent Type Annotations
  src/opera_disp_tms/__main__.py
  src/opera_disp_tms/create_tile_map.py
  src/opera_disp_tms/frames.py
  src/opera_disp_tms/generate_metadata_tile.py
  src/opera_disp_tms/generate_sw_disp_tile.py
  src/opera_disp_tms/generate_sw_vel_tile.py
  src/opera_disp_tms/s3_xarray.py
  src/opera_disp_tms/utils.py
  tests/test_main.py
Labels: bumpless

#51 update EDL information in README.md
  README.md
Labels: bumpless

#52 Remove unused `frame` argument from function call
  src/opera_disp_tms/generate_sw_vel_tile.py
Labels: bumpless

#53 Remove Unused `frame` variable and Update Changelog
  CHANGELOG.md
  src/opera_disp_tms/generate_sw_vel_tile.py
Labels: bumpless

#54 Release v0.4.0
  .github/workflows/create-jira-issue.yml
  .github/workflows/test-and-build.yml
  .github/workflows/test.yml
  CHANGELOG.md
  Dockerfile
  README.md
  environment.yml
  pyproject.toml
  src/opera_disp_tms/__main__.py
  src/opera_disp_tms/create_tile_map.py
  src/opera_disp_tms/etc/entrypoint.sh
  src/opera_disp_tms/find_california_dataset.py
  src/opera_disp_tms/frames.py
  src/opera_disp_tms/generate_metadata_tile.py
  src/opera_disp_tms/generate_sw_disp_tile.py
  src/opera_disp_tms/generate_sw_vel_tile.py
  src/opera_disp_tms/s3_xarray.py
  src/opera_disp_tms/search.py
  src/opera_disp_tms/tmp_s3_access.py
  src/opera_disp_tms/utils.py
  tests/test_generate_sw_disp_tile.py
  tests/test_main.py
  tests/test_search.py
  tests/test_tmp_s3_access.py
  tests/test_utils.py
Labels: minor

#55 implement cmr pagination
  src/opera_disp_tms/search.py
Labels: bumpless

#56 remove obsolete parameter from docstring
  src/opera_disp_tms/generate_sw_vel_tile.py
Labels: bumpless

#60 Release v0.4.1
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  environment.yml
  pyproject.toml
  scripts/make_cal_meta_tiles.py
  src/opera_disp_tms/__main__.py
  src/opera_disp_tms/create_tile_map.py
  src/opera_disp_tms/frames.py
  src/opera_disp_tms/generate_metadata_tile.py
  src/opera_disp_tms/generate_sw_disp_tile.py
  src/opera_disp_tms/generate_sw_vel_tile.py
  src/opera_disp_tms/search.py
  src/opera_disp_tms/utils.py
  tests/test_create_tile_map.py
  tests/test_generate_frame_tile.py
  tests/test_search.py
Labels: patch
