Repository ASFHyP3/OPERA-DISP-TMS, pull requests merged in 2024-10, with the labels that each got.

#5 Account for missing data during metadata tile generation
  src/opera_disp_tms/generate_frame_tile.py
Labels: bumpless

#6 Fix reverse if statement
  src/opera_disp_tms/generate_frame_tile.py
Labels: bumpless

#7 Update metadata tile generation based on review
  README.md
  src/opera_disp_tms/generate_frame_tile.py
  src/opera_disp_tms/generate_sw_disp_tile.py
  src/opera_disp_tms/tmp_s3_access.py
  src/opera_disp_tms/utils.py
  tests/test_generate_frame_tile.py
  tests/test_utils.py
Labels: bumpless

#9 use explicit resampling algorithms in create_tile_map.py
  src/opera_disp_tms/create_tile_map.py
Labels: bumpless

#15 Release review feedback incorporation
  README.md
  src/opera_disp_tms/generate_coh_tiles.py
  src/opera_disp_tms/generate_frame_tile.py
  src/opera_disp_tms/generate_sw_disp_tile.py
  src/opera_disp_tms/tmp_s3_access.py
Labels: bumpless

#14 Release v0.1.0
  .gitignore
  CHANGELOG.md
  Design.md
  README.md
  assets/frame_ordered_overlap.png
  environment.yml
  pyproject.toml
  src/opera_disp_tms/__main__.py
  src/opera_disp_tms/create_tile_map.py
  src/opera_disp_tms/find_california_dataset.py
  src/opera_disp_tms/frames.py
  src/opera_disp_tms/generate_frame_tile.py
  src/opera_disp_tms/generate_sw_disp_tile.py
  src/opera_disp_tms/process.py
  src/opera_disp_tms/s3_xarray.py
  src/opera_disp_tms/tmp_s3_access.py
  src/opera_disp_tms/utils.py
  tests/test_frame.py
  tests/test_generate_frame_tile.py
  tests/test_generate_sw_disp_tile.py
  tests/test_utils.py
Labels: minor

#17 Release v0.1.1
  CHANGELOG.md
  src/opera_disp_tms/create_tile_map.py
Labels: patch

#13 Update geographic reference point to UTM, update reference point names
  Design.md
  src/opera_disp_tms/generate_frame_tile.py
  src/opera_disp_tms/generate_sw_disp_tile.py
  src/opera_disp_tms/s3_xarray.py
  tests/test_generate_sw_disp_tile.py
Labels: bumpless

#20 Release v0.1.2
  CHANGELOG.md
  Design.md
  src/opera_disp_tms/create_tile_map.py
  src/opera_disp_tms/generate_frame_tile.py
  src/opera_disp_tms/generate_sw_disp_tile.py
  src/opera_disp_tms/s3_xarray.py
  src/opera_disp_tms/utils.py
  tests/test_create_tile_map.py
  tests/test_generate_sw_disp_tile.py
  tests/test_utils.py
Labels: patch

#26 Fix readme typo
  README.md
Labels: bumpless

#25 Release v0.2.0
  CHANGELOG.md
  README.md
  pyproject.toml
  scripts/cal_corners.txt
  scripts/make_cal_meta_tiles.py
  scripts/make_cal_sw_disp_tiles.py
  src/opera_disp_tms/generate_metadata_tile.py
  tests/test_generate_frame_tile.py
Labels: minor
