Repository ASFHyP3/OPERA-DISP-TMS, pull requests merged in 2025-02, with the labels that each got.

#89 update s3 stubs for integrity checks introduced in boto3==1.36.0
  environment.yml
  pyproject.toml
  tests/test_utils.py
Labels: bumpless

#93 Update README.md
  README.md
Labels: bumpless

#92 Release v0.7.0
  .github/CODEOWNERS
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-checklist-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  .gitignore
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  Design.md
  Dockerfile
  README.md
  environment.yml
  pyproject.toml
  scripts/cal_corners.txt
  scripts/make_cal_meta_tiles.py
  scripts/make_cal_tiles.py
  src/opera_disp_tms/__main__.py
  src/opera_disp_tms/create_measurement_geotiff.py
  src/opera_disp_tms/create_tile_map.py
  src/opera_disp_tms/data/frame_directions.json
  src/opera_disp_tms/frames.py
  src/opera_disp_tms/generate_metadata_tile.py
  src/opera_disp_tms/generate_sw_disp_tile.py
  src/opera_disp_tms/generate_sw_vel_tile.py
  src/opera_disp_tms/prep_stack.py
  src/opera_disp_tms/s3_xarray.py
  src/opera_disp_tms/utils.py
  tests/conftest.py
  tests/test_create_measurement_geotiff.py
  tests/test_create_tile_map.py
  tests/test_entrypoints.py
  tests/test_frame.py
  tests/test_generate_frame_tile.py
  tests/test_generate_sw_disp_tile.py
  tests/test_generate_sw_vel_tile.py
  tests/test_integration.py
  tests/test_main.py
  tests/test_utils.py
Labels: minor

#91 Update tests to moto3
  tests/test_utils.py
Labels: bumpless

#99 Fix array type conversion bug
  src/opera_disp_tms/create_measurement_geotiff.py
  tests/test_create_measurement_geotiff.py
Labels: bumpless

#100 test_download_geotiffs uses tmp path to download files
  src/opera_disp_tms/create_tile_map.py
  tests/test_create_tile_map.py
Labels: bumpless

#101 Preserve 0 as nodata value
  src/opera_disp_tms/create_tile_map.py
Labels: bumpless

#96 Release v0.8.0
  CHANGELOG.md
  src/opera_disp_tms/constants.py
  src/opera_disp_tms/create_measurement_geotiff.py
  src/opera_disp_tms/create_tile_map.py
  tests/test_create_measurement_geotiff.py
  tests/test_create_tile_map.py
  tests/test_utils.py
Labels: minor

#102 delete repo CoC in favor of organization default
  CODE_OF_CONDUCT.md
Labels: bumpless

#107 Release v0.8.1
  .github/dependabot.yml
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-checklist-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  environment.yml
  pyproject.toml
  requirements-static.txt
  src/opera_disp_tms/prep_stack.py
  src/opera_disp_tms/search.py
  tests/test_prep_stack.py
  tests/test_search.py
Labels: patch
