Repository ASFHyP3/OPERA-DISP-TMS, pull requests merged in 2025-01, with the labels that each got.

#64 Add coords and frame_id to starting DataArray
  src/opera_disp_tms/generate_sw_vel_tile.py
  tests/test_generate_sw_vel_tile.py
Labels: bumpless

#65 Update to fix network connection issue
  src/opera_disp_tms/__main__.py
  src/opera_disp_tms/generate_sw_disp_tile.py
  src/opera_disp_tms/generate_sw_vel_tile.py
  src/opera_disp_tms/prep_stack.py
  tests/test_generate_sw_disp_tile.py
  tests/test_generate_sw_vel_tile.py
  tests/test_prep_stack.py
Labels: bumpless

#66 Add integration tests for displacement/secant_velocity/velocity with a light refactor
  pyproject.toml
  src/opera_disp_tms/generate_sw_vel_tile.py
  src/opera_disp_tms/prep_stack.py
  tests/test_integration.py
Labels: bumpless

#67 Release v0.5.0
  CHANGELOG.md
  pyproject.toml
  src/opera_disp_tms/__main__.py
  src/opera_disp_tms/generate_metadata_tile.py
  src/opera_disp_tms/generate_sw_disp_tile.py
  src/opera_disp_tms/generate_sw_vel_tile.py
  src/opera_disp_tms/prep_stack.py
  src/opera_disp_tms/search.py
  src/opera_disp_tms/utils.py
  tests/test_generate_sw_disp_tile.py
  tests/test_integration.py
  tests/test_prep_stack.py
  tests/test_search.py
  tests/test_utils.py
Labels: minor

#69 Release v0.5.1
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  environment.yml
  pyproject.toml
  scripts/make_cal_meta_tiles.py
  scripts/make_cal_tiles.py
  src/opera_disp_tms/frames.py
  src/opera_disp_tms/generate_metadata_tile.py
  src/opera_disp_tms/generate_sw_disp_tile.py
  src/opera_disp_tms/prep_stack.py
  src/opera_disp_tms/search.py
  src/opera_disp_tms/utils.py
  tests/test_generate_frame_tile.py
  tests/test_integration.py
  tests/test_prep_stack.py
  tests/test_search.py
  tests/test_utils.py
Labels: patch

#70 upgrade mypy action
  .github/workflows/static-analysis.yml
  environment.yml
  pyproject.toml
Labels: bumpless

#74 round scale range to 3 decimal places
  src/opera_disp_tms/create_tile_map.py
  tests/test_create_tile_map.py
Labels: bumpless

#76 Fix type of scale parameters
  src/opera_disp_tms/create_tile_map.py
Labels: bumpless

#73 Release v0.6.0
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  environment.yml
  pyproject.toml
  src/opera_disp_tms/create_tile_map.py
  tests/test_create_tile_map.py
Labels: minor

#77 update code of conduct per guidance from NASA
  CODE_OF_CONDUCT.md
Labels: bumpless

#82 Update CODEOWNERS
  .github/CODEOWNERS
Labels: bumpless

#84 upload files to s3 in parallel
  src/opera_disp_tms/utils.py
  tests/test_utils.py
Labels: bumpless

#86 fix open_opera_disp_granule type hint
  src/opera_disp_tms/s3_xarray.py
Labels: bumpless
